# Generated by Django 3.0.5 on 2022-01-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTable1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='date_item',
            new_name='DateItem',
        ),
    ]
