# Generated by Django 3.0.5 on 2022-01-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyTable1', '0003_auto_20220106_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateitem',
            old_name='date1',
            new_name='last_activity_date',
        ),
        migrations.RenameField(
            model_name='dateitem',
            old_name='date2',
            new_name='registration_date',
        ),
    ]
